version: 2
sources:
  - name: staging
    description: >
      This source contains Eurostat dataset: "Gross domestic product (GDP) at current market prices by NUTS 2 regions".
      Dataset code in the Eurostat classification: nama_10r_2gdp.
    database: free-tier-project-397608
    schema: eurostat_gdp_raw
    tables:
        - name: nama-10r-2gdp

models:
    - name: stg_nama-10r-2gdp
      description: >
        The model takes all data from the source "staging.nama-10r-2gdp" AS-IS,
        and makes some renamings of the fields.  
      columns:
        - name: unit
          description: Unit of measure
          tests:
            - not_null:
                  severity: warn
        - name: geo
          description: Geopolitical entity (reporting)
          tests:
            - not_null:
                  severity: warn
        - name: string_field_2
          description: The target value in the unit of measure for 2021 year
        - name: string_field_3
          description: The target value in the unit of measure for 2020 year
        - name: string_field_4
          description: The target value in the unit of measure for 2019 year
        - name: string_field_5
          description: The target value in the unit of measure for 2018 year
        - name: string_field_6
          description: The target value in the unit of measure for 2017 year
        - name: string_field_7
          description: The target value in the unit of measure for 2016 year
        - name: string_field_8
          description: The target value in the unit of measure for 2015 year
        - name: string_field_9
          description: The target value in the unit of measure for 2014 year
        - name: string_field_10
          description: The target value in the unit of measure for 2013 year
        - name: string_field_11
          description: The target value in the unit of measure for 2012 year
        - name: string_field_12
          description: The target value in the unit of measure for 2011 year
        - name: string_field_13
          description: The target value in the unit of measure for 2010 year
        - name: string_field_14
          description: The target value in the unit of measure for 2009 year
        - name: string_field_15
          description: The target value in the unit of measure for 2008 year
        - name: string_field_16
          description: The target value in the unit of measure for 2007 year
        - name: string_field_17
          description: The target value in the unit of measure for 2006 year
        - name: string_field_18
          description: The target value in the unit of measure for 2005 year
        - name: string_field_19
          description: The target value in the unit of measure for 2004 year
        - name: string_field_20
          description: The target value in the unit of measure for 2003 year
        - name: string_field_21
          description: The target value in the unit of measure for 2002 year
        - name: string_field_22
          description: The target value in the unit of measure for 2001 year
        - name: string_field_23
          description: The target value in the unit of measure for 2000 year

